name: "Repost to Bluesky"

on:
  # Run every 1 hour
  schedule:
    - cron: '0 */1 * * *'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  repost:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run repost bot
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
        run: npm start
